-- 大分県の公開ホールデータを日次保存する共通テーブル
create table if not exists public.oita_machine_daily (
  id bigint generated by default as identity primary key,
  play_date date not null,
  prefecture text not null default '大分県',
  city text,
  shop_name text not null,
  machine_name text not null,
  machine_number text not null,
  category text check (category in ('slot','pachinko','unknown')) default 'unknown',
  total_spins integer,
  start_count integer,
  jackpot_count integer,
  first_hit_count integer,
  bb integer,
  rb integer,
  art_at integer,
  combined_probability numeric,
  net_coins integer,
  net_balls integer,
  payout_rate numeric,
  final_spins integer,
  slump_summary text,
  source_name text not null,
  source_url text,
  collected_at timestamptz not null default now(),
  raw_data jsonb not null default '{}'::jsonb,
  unique (play_date, shop_name, machine_name, machine_number, source_name)
);

create index if not exists oita_machine_daily_date_idx on public.oita_machine_daily(play_date desc);
create index if not exists oita_machine_daily_shop_idx on public.oita_machine_daily(shop_name, play_date desc);
create index if not exists oita_machine_daily_machine_idx on public.oita_machine_daily(machine_name, play_date desc);

alter table public.oita_machine_daily enable row level security;

-- 公開分析画面からの読み取り専用。書き込みは service role のみを想定。
drop policy if exists "Public can read Oita machine daily" on public.oita_machine_daily;
create policy "Public can read Oita machine daily"
on public.oita_machine_daily for select
to anon, authenticated
using (true);
